-- Melody Matrix: Batch insert for Metal playlist tracks
INSERT INTO music (title, artist, file_path, cover_image) VALUES
('So Far As I Know', 'Moon Blossoms', 'assets/Metal playlist/001-2245816-So Far As I Know-Moon Blossoms.mp3', NULL),
('REGINA', 'Rot', 'assets/Metal playlist/002-2230318-REGINA-Rot.mp3', NULL),
('Run Lola Run', 'DEAD CITY EMPIRE', 'assets/Metal playlist/003-2190098-DEAD CITY EMPIRE-Run Lola Run.mp3', NULL),
('After Us', 'FROMSKYTOABYSS', 'assets/Metal playlist/004-2132711-FROMSKYTOABYSS-After Us.mp3', NULL),
('Crypt of Insomnia', 'Depersonalization', 'assets/Metal playlist/005-1724488-Crypt of Insomnia-Depersonalization.mp3', NULL),
('Hands of Attrition', 'Solace', 'assets/Metal playlist/006-2063966-Hands of Attrition-Solace.mp3', NULL),
('ENAXWOL', 'DSCN', 'assets/Metal playlist/007-2141017-ENAXWOL-DSCN.mp3', NULL),
('Mahidevran - Parable (Live from LEGEND STUDIO)', 'Mahidevran Rock Band', 'assets/Metal playlist/008-2043262-Mahidevran Rock Band-Mahidevran - Parable _Live from LEGEND STUDIO_.mp3', NULL),
('Other Lives', 'BlacKNetiC', 'assets/Metal playlist/009-2131736-BlacKNetiC-Other Lives.mp3', NULL),
('Fired_', 'Redmind', 'assets/Metal playlist/010-2037041-Redmind-Fired_.mp3', NULL),
('Poison Ring', 'ElisaDay', 'assets/Metal playlist/011-1937749-ElisaDay-Poison Ring.mp3', NULL),
('Road', 'Kolony', 'assets/Metal playlist/012-1169826-Kolony-Road.mp3', NULL),
('Kill City Kills - Ride into the Badlands', 'Kill City Kills', 'assets/Metal playlist/013-1901190-Kill City Kills-Kill City Kills - Ride into the Badlands.mp3', NULL),
('Forgotten Dream', 'The Rinn', 'assets/Metal playlist/014-1530450-The Rinn-Forgotten Dream.mp3', NULL),
('Machinegun', 'Scream Inc.', 'assets/Metal playlist/015-1460214-Scream Inc.-Machinegun.mp3', NULL),
('Nothing To Fear', 'Hide & Dream', 'assets/Metal playlist/016-1484347-Hide _amp_ Dream-2. Nothing To Fear.mp3', NULL),
('Far Away From Home', 'Thornwill', 'assets/Metal playlist/017-615568-Thornwill-Far Away From Home.mp3', NULL),
('Mahidevran - Drifter', 'Mahidevran Rock Band', 'assets/Metal playlist/018-2039138-Mahidevran Rock Band-Mahidevran - Drifter.mp3', NULL),
('Pound-x-_-x-_.+._-', 'Pound', 'assets/Metal playlist/019-1867878-Pound-x-_-x-_.+._-.mp3', NULL),
('Icon', 'Azgard', 'assets/Metal playlist/020-1235059-Azgard-Icon.mp3', NULL),
('Neural Groove', 'Aygan', 'assets/Metal playlist/021-288800-Aygan-Neural Groove.mp3', NULL),
('Wake Up, Don_t Lose It (Don_t Let It Go)', 'One missed may', 'assets/Metal playlist/022-1126948-One missed may-Wake Up, Don_t Lose It _Don_t Let It Go_.mp3', NULL),
('Work Hard Die In Office', 'Acting Like Heroes', 'assets/Metal playlist/023-791167-Acting Like Heroes-Work Hard Die In Office.mp3', NULL),
('The Crows (+ Cristian Machado de Ill Nino)', 'Vendetta Fucking Metal', 'assets/Metal playlist/024-1795724-Vendetta Fucking Metal-The Crows _ + Cristian Machado de Ill Nino_.mp3', NULL),
('Metal Child', 'Avenger Kills', 'assets/Metal playlist/025-1813076-Avenger Kills-Metal Child.mp3', NULL),
('______ ___', 'VintergatA', 'assets/Metal playlist/026-1657875-VintergatA-______ ___.mp3', NULL),
('A Blazing Rage', 'Greyskull Chapel', 'assets/Metal playlist/027-1512411-Greyskull Chapel-A Blazing Rage.mp3', NULL),
('Regrets', 'Danforth', 'assets/Metal playlist/028-69638-Danforth-Regrets.mp3', NULL),
('Amunisi Industri', 'HELLIOST', 'assets/Metal playlist/029-1375792-HELLIOST-Amunisi Industri.mp3', NULL),
('Everflow', 'A Tragedy At Hand', 'assets/Metal playlist/030-1224643-A Tragedy At Hand-Everflow.mp3', NULL),
('Truth Hurts (feat. Alicia Orozco)', 'Denizen', 'assets/Metal playlist/031-1872624-Denizen-Truth Hurts _feat. Alicia Orozco_.mp3', NULL),
('Encephalon', 'VITNE', 'assets/Metal playlist/032-1653948-VITNE-Encephalon.mp3', NULL),
('Aftermath of Illusions', 'Maleficus Angelus', 'assets/Metal playlist/033-1031292-Maleficus Angelus-Aftermath of Illusions.mp3', NULL),
('On The Edge', 'Cardinal Line', 'assets/Metal playlist/034-1708751-Cardinal Line-On The Edge.mp3', NULL),
('Wauld DanZ - For Last Revelation', 'Wauld DanZ', 'assets/Metal playlist/035-1720528-Wauld DanZ-Wauld DanZ - For Last Revelation.mp3', NULL),
('Little sister', 'Insidious One', 'assets/Metal playlist/036-1618434-Insidious One-Little sister.mp3', NULL),
('Living With The Pain', 'Fallen to Flux', 'assets/Metal playlist/037-1187644-Fallen to Flux-Living With The Pain.mp3', NULL),
('Class Trial', 'Swim to Drown', 'assets/Metal playlist/038-1314695-Swim to Drown-Class Trial.mp3', NULL);
